# deploy.yml
name: deploy
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SERVER_PORT: '22'
          FOLDER: ./
          SERVER_IP: ${{ secrets.REMOTE_HOST }}
          USERNAME: ${{ secrets.REMOTE_USER }}
          SERVER_DESTINATION: ${{ secrets.TARGET }}